TrendingTopics =["racisme",
"racism",
"raciste",
"insécurité",
"immigration",
"intersectionnalité",
"intersectionnalite",
"lutte intersectionnelle",
"afroféminisme",
"afro féminisme",
"afrofeminisme",
"afro feminisme",
"fachosphere",
"appropriation culturelle",
"fragilité blanche",
"privilège blanc",
"privilege blanc",
"white privilege",
"white fragility",
"fachosphère",
"islamisme",
"islamiste",
"islamique",
"white supremaciste",
"suprémaciste blanc",
"suprémacisme blanc",
"supremaciste blanc",
"supremacisme blanc",
"white supremacist",
"white supremacism",
"islamo-gauchiste",
"islamogauchiste",
"islamogauchisme",
"islamo-gauchisme",
"islamo gauchiste",
"islamo gauchistes",
"islamo gauchisme",
"radical",
"islamophobie",
"islamophobe",
"antisémitisme",
"antiblanc",
"anti-blanc",
"sionisme",
"sioniste",
"antisioniste",
"antisionisme",
"attentat"]


TrendingTopics = [
"retraites",
"réforme des retraites",
"reforme des retraites",
"reformedesretraites",
"grevistes",
"greviste",
"grève générale",
"greve generale",
"grevegenerale",
"retraite par point",
"retraites par point",
"retraiteparpoint",
"fiers de la grève",
"fiers de la greve",
"fiersdelagreve"
]